---
cluster_name: dcos-vagrant
bootstrap_url: http://boot.dcos
exhibitor_storage_backend: zookeeper
exhibitor_zk_hosts: 192.168.65.50:2181
exhibitor_zk_path: /zk-shared
master_discovery: static
master_list:
- 192.168.65.90
resolvers:
- 10.0.2.3
- 8.8.8.8
ssh_user: vagrant
