cluster_config:
  bootstrap_url: http://boot.dcos:8888
  cluster_name: dcos
  exhibitor_storage_backend: zookeeper
  exhibitor_zk_hosts: boot.dcos:3181
  exhibitor_zk_path: /dcos
  master_discovery: static
  master_list:
    - 192.168.65.90
    - 192.168.65.91
    - 192.168.65.92
  resolvers:
    - 192.168.121.1
    - 8.8.4.4
  roles: slave_public
  weights: slave_public=1

ssh_config:
  log_directory: /genconf/logs
